#!/usr/bin/env sh
rm $HOME/.spacemacs.d/dotfiles/.zshrc
rm $HOME/.spacemacs.d/dotfiles/.zshenv
rm $HOME/.spacemacs.d/dotfiles/.tmux.conf

cp $HOME/.zshrc ~/.spacemacs.d/dotfiles
cp $HOME/.zshenv ~/.spacemacs.d/dotfiles
cp $HOME/.tmux.conf ~/.spacemacs.d/dotfiles

echo "Files have updated."
